name: build

on:
  push:
    paths:
      - 'src/**'
      - '**/build.yml'

jobs:
  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "hello"
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip

      - name: template build
        working-directory: src/template
        run: |
          platformio run -d ${{ matrix.example }}

  IDF:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Install ESP-IDF
        uses: CalinRadoni/esp-idf-v4-action@v2
        with:
          esp_idf_version: 'latest'

      - name: Build Rainbow-LED-Strip
        working-directory: src/demo/Rainbow-LED-Strip
        run: |
          source ~/esp/esp-idf/export.sh
          idf.py build

      - name: Build esp32c3_sandbox
        working-directory: src/demo/esp32c3_sandbox
        run: |
          source ~/esp/esp-idf/export.sh
          idf.py build
          idf.py reconfigure
          idf.py app
          idf.py size

  # Docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: "recursive"
  #         fetch-depth: 1

  #     - name: Build the code
  #       working-directory: src/demo/esp32c3_sandbox
  #       uses: CalinRadoni/esp-idf-v4-container-action@v4.1
  #       id: esp-idf-build

  #     - name: Show the exit code
  #       run: echo "The exit code was ${{ steps.esp-idf-build.outputs.result }}"
